export const CLERK_CODE = {
  CLERK_MISSING_RAW_BODY: 'CLERK_MISSING_RAW_BODY',
  CLERK_MISSING_SVIX_HEADERS: 'CLERK_MISSING_SVIX_HEADERS',
  CLERK_INVALID_SIGNATURE: 'CLERK_INVALID_SIGNATURE',
  CLERK_INVALID_PAYLOAD: 'CLERK_INVALID_PAYLOAD',
} as const;
