export const RATE_LIMIT_CODE = {
  RATE_LIMIT_INVALID_IDENTIFIER_CONTENT: 'RATE_LIMIT_INVALID_IDENTIFIER_CONTENT',
  RATE_LIMIT_INVALID_CONTEXT: 'RATE_LIMIT_INVALID_CONTEXT',
  RATE_LIMIT_EXECUTION_FAILED: 'RATE_LIMIT_EXECUTION_FAILED',
} as const;
