import { ErrorCode } from '@/error/code/error.code';
import { ErrorSeverity } from '@/error/error.enum';

export const ERROR_METADATA: Record<ErrorCode, { status: number; severity: ErrorSeverity }> = {
  // * REDIS:
  REDIS_INVALID_TTL_DURATION: { status: 400, severity: ErrorSeverity.LOW },
  REDIS_INVALID_SECONDS_DURATION: { status: 400, severity: ErrorSeverity.LOW },

  // * RATE LIMIT:
  RATE_LIMIT_INVALID_IDENTIFIER_CONTENT: { status: 400, severity: ErrorSeverity.LOW },
  RATE_LIMIT_INVALID_CONTEXT: { status: 400, severity: ErrorSeverity.LOW },
  RATE_LIMIT_EXECUTION_FAILED: { status: 500, severity: ErrorSeverity.HIGH },

  // * COMMON:
  COMMON_INTERNAL_ERROR: { status: 500, severity: ErrorSeverity.HIGH },

  // * HTTP:
  HTTP_CONTINUE: { status: 100, severity: ErrorSeverity.LOW },
  HTTP_SWITCHING_PROTOCOLS: { status: 101, severity: ErrorSeverity.LOW },
  HTTP_PROCESSING: { status: 102, severity: ErrorSeverity.LOW },
  HTTP_EARLYHINTS: { status: 103, severity: ErrorSeverity.LOW },
  HTTP_OK: { status: 200, severity: ErrorSeverity.LOW },
  HTTP_CREATED: { status: 201, severity: ErrorSeverity.LOW },
  HTTP_ACCEPTED: { status: 202, severity: ErrorSeverity.LOW },
  HTTP_NON_AUTHORITATIVE_INFORMATION: { status: 203, severity: ErrorSeverity.LOW },
  HTTP_NO_CONTENT: { status: 204, severity: ErrorSeverity.LOW },
  HTTP_RESET_CONTENT: { status: 205, severity: ErrorSeverity.LOW },
  HTTP_PARTIAL_CONTENT: { status: 206, severity: ErrorSeverity.LOW },
  HTTP_MULTI_STATUS: { status: 207, severity: ErrorSeverity.LOW },
  HTTP_ALREADY_REPORTED: { status: 208, severity: ErrorSeverity.LOW },
  HTTP_CONTENT_DIFFERENT: { status: 210, severity: ErrorSeverity.LOW },
  HTTP_AMBIGUOUS: { status: 300, severity: ErrorSeverity.LOW },
  HTTP_MOVED_PERMANENTLY: { status: 301, severity: ErrorSeverity.LOW },
  HTTP_FOUND: { status: 302, severity: ErrorSeverity.LOW },
  HTTP_SEE_OTHER: { status: 303, severity: ErrorSeverity.LOW },
  HTTP_NOT_MODIFIED: { status: 304, severity: ErrorSeverity.LOW },
  HTTP_TEMPORARY_REDIRECT: { status: 307, severity: ErrorSeverity.LOW },
  HTTP_PERMANENT_REDIRECT: { status: 308, severity: ErrorSeverity.LOW },
  HTTP_BAD_REQUEST: { status: 400, severity: ErrorSeverity.LOW },
  HTTP_UNAUTHORIZED: { status: 401, severity: ErrorSeverity.MEDIUM },
  HTTP_PAYMENT_REQUIRED: { status: 402, severity: ErrorSeverity.LOW },
  HTTP_FORBIDDEN: { status: 403, severity: ErrorSeverity.MEDIUM },
  HTTP_NOT_FOUND: { status: 404, severity: ErrorSeverity.LOW },
  HTTP_METHOD_NOT_ALLOWED: { status: 405, severity: ErrorSeverity.LOW },
  HTTP_NOT_ACCEPTABLE: { status: 406, severity: ErrorSeverity.LOW },
  HTTP_PROXY_AUTHENTICATION_REQUIRED: { status: 407, severity: ErrorSeverity.MEDIUM },
  HTTP_REQUEST_TIMEOUT: { status: 408, severity: ErrorSeverity.MEDIUM },
  HTTP_CONFLICT: { status: 409, severity: ErrorSeverity.LOW },
  HTTP_GONE: { status: 410, severity: ErrorSeverity.LOW },
  HTTP_LENGTH_REQUIRED: { status: 411, severity: ErrorSeverity.LOW },
  HTTP_PRECONDITION_FAILED: { status: 412, severity: ErrorSeverity.LOW },
  HTTP_PAYLOAD_TOO_LARGE: { status: 413, severity: ErrorSeverity.LOW },
  HTTP_URI_TOO_LONG: { status: 414, severity: ErrorSeverity.LOW },
  HTTP_UNSUPPORTED_MEDIA_TYPE: { status: 415, severity: ErrorSeverity.LOW },
  HTTP_REQUESTED_RANGE_NOT_SATISFIABLE: { status: 416, severity: ErrorSeverity.LOW },
  HTTP_EXPECTATION_FAILED: { status: 417, severity: ErrorSeverity.LOW },
  HTTP_I_AM_A_TEAPOT: { status: 418, severity: ErrorSeverity.LOW },
  HTTP_MISDIRECTED: { status: 421, severity: ErrorSeverity.LOW },
  HTTP_UNPROCESSABLE_ENTITY: { status: 422, severity: ErrorSeverity.LOW },
  HTTP_LOCKED: { status: 423, severity: ErrorSeverity.LOW },
  HTTP_FAILED_DEPENDENCY: { status: 424, severity: ErrorSeverity.LOW },
  HTTP_PRECONDITION_REQUIRED: { status: 428, severity: ErrorSeverity.LOW },
  HTTP_TOO_MANY_REQUESTS: { status: 429, severity: ErrorSeverity.MEDIUM },
  HTTP_UNRECOVERABLE_ERROR: { status: 456, severity: ErrorSeverity.MEDIUM },
  HTTP_INTERNAL_SERVER_ERROR: { status: 500, severity: ErrorSeverity.HIGH },
  HTTP_NOT_IMPLEMENTED: { status: 501, severity: ErrorSeverity.HIGH },
  HTTP_BAD_GATEWAY: { status: 502, severity: ErrorSeverity.HIGH },
  HTTP_SERVICE_UNAVAILABLE: { status: 503, severity: ErrorSeverity.HIGH },
  HTTP_GATEWAY_TIMEOUT: { status: 504, severity: ErrorSeverity.HIGH },
  HTTP_HTTP_VERSION_NOT_SUPPORTED: { status: 505, severity: ErrorSeverity.HIGH },
  HTTP_INSUFFICIENT_STORAGE: { status: 507, severity: ErrorSeverity.HIGH },
  HTTP_LOOP_DETECTED: { status: 508, severity: ErrorSeverity.HIGH },
};
